# Mehrere Zellen im Standard-Grid
title: Sicherheit / Zugriff
views:
  - title: Kameras
    path: kameras
    cards:
      - type: grid
        columns: 2
        square: false
        cards:
          - type: custom:hikvision-access-overview-card
            device: hintereingang_halle
            title: Hintereingang Halle
          - type: custom:hikvision-access-overview-card
            device: nebeneingang
            title: Nebeneingang
